# Generated by Django 6.0.2 on 2026-03-20 18:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_risk_models_and_subscription_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_channel', models.CharField(choices=[('mobile', 'Mobile'), ('siem', 'SIEM'), ('edr', 'EDR'), ('waf', 'WAF'), ('manual', 'Manual')], default='mobile', max_length=20)),
                ('process_name', models.CharField(default='mobile_access', max_length=100)),
                ('attack_pattern', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('asset_criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('likelihood_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('impact_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('control_strength_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('residual_risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rules_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('anomaly_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sequence_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('triage', 'Triage'), ('contained', 'Contained'), ('closed', 'Closed')], default='open', max_length=20)),
                ('recommended_action', models.TextField(blank=True)),
                ('explainability_payload', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('rule_version', models.CharField(blank=True, max_length=50)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_cases', to='core.organization')),
            ],
            options={
                'db_table': 'risk_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskEngineVersionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_type', models.CharField(choices=[('rules', 'Rules'), ('model', 'Model'), ('fusion', 'Fusion')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_engine_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('input', 'Input'), ('features', 'Features'), ('scoring', 'Scoring'), ('decision', 'Decision')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('risk_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.riskcase')),
            ],
            options={
                'db_table': 'risk_evidences',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskcase',
            index=models.Index(fields=['source_channel', '-created_at'], name='risk_cases_source__ee4637_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcase',
            index=models.Index(fields=['status', '-created_at'], name='risk_cases_status_b9431c_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcase',
            index=models.Index(fields=['organization', '-created_at'], name='risk_cases_organiz_d001b7_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcase',
            index=models.Index(fields=['residual_risk_score'], name='risk_cases_residua_d69f6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskengineversionlog',
            unique_together={('engine_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='riskevidence',
            index=models.Index(fields=['risk_case', 'evidence_type'], name='risk_eviden_risk_ca_0242dc_idx'),
        ),
    ]
