# Generated by Django 5.2.7 on 2025-10-08 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('scan_summary', 'Resumen de Escaneo'), ('threat_analysis', 'Análisis de Amenazas'), ('detailed_report', 'Reporte Detallado'), ('executive_summary', 'Resumen Ejecutivo')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('json', 'JSON'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('include_screenshots', models.BooleanField(default=False)),
                ('include_technical_details', models.BooleanField(default=True)),
                ('include_recommendations', models.BooleanField(default=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.fileupload')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_scans', 'Total de Escaneos'), ('threats_detected', 'Amenazas Detectadas'), ('clean_files', 'Archivos Limpios'), ('scan_duration', 'Duración de Escaneos'), ('detection_rate', 'Tasa de Detección')], max_length=30)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(blank=True, max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.report')),
            ],
            options={
                'verbose_name': 'Métrica de Reporte',
                'verbose_name_plural': 'Métricas de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('scan_summary', 'Resumen de Escaneo'), ('threat_analysis', 'Análisis de Amenazas'), ('detailed_report', 'Reporte Detallado'), ('executive_summary', 'Resumen Ejecutivo')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('json', 'JSON'), ('csv', 'CSV')], max_length=10)),
                ('template_content', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'unique_together': {('report_type', 'format', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('on_detection', 'Al Detectar Amenaza')], max_length=20)),
                ('email_recipients', models.TextField(help_text='Emails separados por comas')),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Programación de Reporte',
                'verbose_name_plural': 'Programaciones de Reportes',
            },
        ),
    ]
